spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-management-route
          uri: lb://PRODUCT-MANAGEMENT
          predicates:
            - Path=/products/**
        - id: cart-management-route
          uri: lb://CART-MANAGEMENT
          predicates:
            - Path=/cart/**
        - id: cart-management-route
          uri: lb://CART-MANAGEMENT
          predicates:
            - Path=/purchases/**
        - id: profile-management-route
          uri: https://ecommerce-profile-service.onrender.com
          predicates:
            - Path=/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"

eureka:
  client:
    service-url:
     defaultZone: https://eureka-for-ecommerce.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
      
server:
  port: 9000
