spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-management-route
          uri: https://ecommerce-product-management.onrender.com
          predicates:
            - Path=/products/**
        - id: cart-management-route
          uri: https://ecommerce-cart-service.onrender.com
          predicates:
            - Path=/cart/**
        - id: cart-management-route
          uri: https://ecommerce-cart-service.onrender.com
          predicates:
            - Path=/purchases/**
        - id: profile-management-route
          uri: https://ecommerce-profile-service.onrender.com
          predicates:
            - Path=/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
      
server:
  port: 9000
